[package]
name = "dict_quiz"
version = "0.1.0"
edition = "2024"
description = "App to make interactive quizes out of Swedish dictionary."

[dependencies]
clearscreen = "4.0.2"
csv = "1.3.1"
rand = "0.9.2"
serde = { version = "1", features = ["derive"] }
